"""
API Schemas
"""

from .auth import (
    LoginRequest,
    LoginResponse,
    RegisterRequest,
    TokenPayload,
    RefreshTokenRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
)
from .data_source import (
    DataSourceCreate,
    DataSourceUpdate,
    DataSourceResponse,
    DataSourceTestConnection,
    DataSourceTestResponse,
    DataSourceListResponse,
    DataSourceType,
    DataSourceStatus,
)
from .query import (
    QueryCreate,
    QueryExecuteRequest,
    QueryResponse,
    QueryListResponse,
    QueryAnalytics,
    QueryTemplateCreate,
    QueryTemplateUpdate,
    QueryTemplateResponse,
    QueryStatus,
    QueryLanguage,
)
from .schema import (
    ColumnInfo,
    TableInfo,
    SchemaInfo,
    SchemaListResponse,
    TableListResponse,
    SchemaDetailResponse,
    SchemaRefreshRequest,
    SchemaRefreshResponse,
    SchemaSearchRequest,
    SchemaSearchResponse,
    SchemaDiffRequest,
    SchemaDiffResponse,
)
from .agent import (
    AgentRequest,
    AgentResponse,
    QueryAgentRequest,
    QueryAgentResponse,
    DesignAgentRequest,
    DesignAgentResponse,
    SupportAgentRequest,
    SupportAgentResponse,
    AgentHealthResponse,
    AgentAnalytics,
    AgentConfigUpdate,
    AgentType,
    AgentStatus,
    LLMProvider,
)

__all__ = [
    # Auth schemas
    "LoginRequest",
    "LoginResponse",
    "RegisterRequest",
    "TokenPayload",
    "RefreshTokenRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    # Data source schemas
    "DataSourceCreate",
    "DataSourceUpdate",
    "DataSourceResponse",
    "DataSourceTestConnection",
    "DataSourceTestResponse",
    "DataSourceListResponse",
    "DataSourceType",
    "DataSourceStatus",
    # Query schemas
    "QueryCreate",
    "QueryExecuteRequest",
    "QueryResponse",
    "QueryListResponse",
    "QueryAnalytics",
    "QueryTemplateCreate",
    "QueryTemplateUpdate",
    "QueryTemplateResponse",
    "QueryStatus",
    "QueryLanguage",
    # Schema schemas
    "ColumnInfo",
    "TableInfo",
    "SchemaInfo",
    "SchemaListResponse",
    "TableListResponse",
    "SchemaDetailResponse",
    "SchemaRefreshRequest",
    "SchemaRefreshResponse",
    "SchemaSearchRequest",
    "SchemaSearchResponse",
    "SchemaDiffRequest",
    "SchemaDiffResponse",
    # Agent schemas
    "AgentRequest",
    "AgentResponse",
    "QueryAgentRequest",
    "QueryAgentResponse",
    "DesignAgentRequest",
    "DesignAgentResponse",
    "SupportAgentRequest",
    "SupportAgentResponse",
    "AgentHealthResponse",
    "AgentAnalytics",
    "AgentConfigUpdate",
    "AgentType",
    "AgentStatus",
    "LLMProvider",
]
